[package]
name = "s9_binance_codec"
version = "0.0.1"
edition = "2021"
authors = ["Alexander Silvennoinen <alex@silvennoinen.de>"]

[lib]
name = "s9_binance_codec"
path = "src/lib.rs"

[dependencies]
serde = {version = "1.0", default-features = false, features = ["derive"]}
serde_json = "1.0"